_index:
    path:     /
    defaults: { _controller: "WCSCoavBundle:Flight:index" }
    methods:  GET

_show:
    path:     /{id}/show
    defaults: { _controller: "WCSCoavBundle:Flight:show" }
    methods:  GET

_new:
    path:     /new
    defaults: { _controller: "WCSCoavBundle:Flight:new" }
    methods:  [GET, POST]

_edit:
    path:     /{id}/edit
    defaults: { _controller: "WCSCoavBundle:Flight:edit" }
    methods:  [GET, POST]

_delete:
    path:     /{id}/delete
    defaults: { _controller: "WCSCoavBundle:Flight:delete" }
    methods:  DELETE
