_index:
    path:     /
    defaults: { _controller: "WCSCoavBundle:Reservation:index" }
    methods:  GET

_show:
    path:     /{id}/show
    defaults: { _controller: "WCSCoavBundle:Reservation:show" }
    methods:  GET

_new:
    path:     /new
    defaults: { _controller: "WCSCoavBundle:Reservation:new" }
    methods:  [GET, POST]

_edit:
    path:     /{id}/edit
    defaults: { _controller: "WCSCoavBundle:Reservation:edit" }
    methods:  [GET, POST]

_delete:
    path:     /{id}/delete
    defaults: { _controller: "WCSCoavBundle:Reservation:delete" }
    methods:  DELETE
