wcs_coav:
    resource: "@WCSCoavBundle/Resources/config/routing/terrain.yml"
    prefix:   /terrain


_index:
    path:     /
    defaults: { _controller: "WCSCoavBundle:Terrain:index" }
    methods:  GET

_show:
    path:     /{id}/show
    defaults: { _controller: "WCSCoavBundle:Terrain:show" }
    methods:  GET



