wcs_coav_planemodel:
        resource: "@WCSCoavBundle/Resources/config/routing/planemodel.yml"
        prefix:   /planemodel

wcs_coav:
    resource: "@WCSCoavBundle/Resources/config/routing/flight.yml"
    prefix:   /flight

wcs_coav:
    resource: "@WCSCoavBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation

wcs_coav:
    resource: "@WCSCoavBundle/Resources/config/routing/terrain.yml"
    prefix:   /terrain


wcs_coav_homepage:
    path:     /
    defaults: { _controller: WCSCoavBundle:Default:index }
